// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:skiffy/api/frb_generated.dart';
import 'package:skiffy/api/lib.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixClient>>
abstract class MatrixClient implements RustOpaqueInterface {
  Future<OwnedUserId?> getUserInfo();

  Future<bool> isLoggedIn();

  Future<void> login({required String username, required String password});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MatrixClient> newInstance({
    required String homeServerUrl,
    bool? disableRetries,
  }) => RustLib.instance.api.crateMatrixClientStructsMatrixClientNew(
    homeServerUrl: homeServerUrl,
    disableRetries: disableRetries,
  );

  Future<void> sendMessage({required String roomId, required String message});

  Future<void> sync_();
}
