# Pre-commit hooks for design system compliance
repos:
  - repo: local
    hooks:
      # - id: flutter-lint
      #   name: Flutter Lint
      #   entry: make lint
      #   language: system
      #   files: '\.dart$'
      #   exclude: '^(lib/app/design_system/|test/app/design_system/)'
      #   fail_fast: true
      #   pass_filenames: false

      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        files: '\.dart$'
        pass_filenames: false

      - id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
        files: '\.dart$'
        pass_filenames: false