name: skiffy
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  dotted_border: ^3.1.0
  auto_route: ^10.1.2
  rust_lib_skiffy:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0

  collection: any
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  flutter_svg: ^2.0.10+1
dev_dependencies:
  very_good_analysis: ^9.0.0
  auto_route_generator: ^10.2.4
  freezed: ^3.2.0
  build_runner: ^2.7.1
  json_serializable: ^6.7.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  ffi: ^2.1.3
  ffigen: ^13.0.0
  mockito: ^5.5.0
  flutter_gen_runner: ^5.11.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icons/
    - .env
    - .env.development
    - .env.staging
    - .env.production

  # Custom fonts for Design System
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
