[package]
name = "retrievly"
version = "1.0.0"
edition = "2021"

[dependencies]
tauri = { version = "2.1", features = [] }
tauri-plugin-fs = "2.1"
tauri-plugin-shell = "2.1"
tauri-plugin-notification = "2.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
