// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:skiffy/rust/frb_generated.dart';

part 'storage.freezed.dart';

@freezed
sealed class SecureStorageError with _$SecureStorageError {
  const SecureStorageError._();

  /// The key was not found in storage
  const factory SecureStorageError.keyNotFound({
    required String key,
  }) = SecureStorageError_KeyNotFound;

  /// Access was denied by the storage backend
  const factory SecureStorageError.accessDenied({
    required String key,
  }) = SecureStorageError_AccessDenied;

  /// The storage backend is not available
  const factory SecureStorageError.backendNotAvailable({
    required String reason,
  }) = SecureStorageError_BackendNotAvailable;

  /// Invalid input was provided
  const factory SecureStorageError.invalidInput({
    required String message,
  }) = SecureStorageError_InvalidInput;

  /// An internal error occurred
  const factory SecureStorageError.internal({
    required String message,
  }) = SecureStorageError_Internal;
}
