// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:skiffy/rust/core/storage.dart';
import 'package:skiffy/rust/frb_generated.dart';

// These functions are ignored because they have generic arguments: `clear`, `delete`, `get`, `set`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryStorage>>
abstract class InMemoryStorage implements RustOpaqueInterface, SecureStorage {
  static Future<InMemoryStorage> default_() =>
      RustLib.instance.api.crateCoreStorageMemoryInMemoryStorageDefault();

  @override
  Future<SessionStatus> isPersistent();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new in-memory storage instance
  ///
  /// # Returns
  ///
  /// Returns a new `InMemoryStorage` with an empty data store.
  static Future<InMemoryStorage> newInstance() =>
      RustLib.instance.api.crateCoreStorageMemoryInMemoryStorageNew();
}
