/**
 * Post formatting utilities
 * Migrated from: vendor/desktop/webapp/channels/src/utils/post_utils.ts
 *
 * Provides helper functions for post type checking, formatting, and metadata extraction.
 */

import type { IPost, IFileInfo } from "@/types";

import { isToday, isYesterday, getRelativeTime, formatDateTime } from "./date";
import { truncateText } from "./text-formatting";

//#region Constants

/**
 * Prefix for all system message post types.
 * System posts include: system_join_channel, system_leave_channel,
 * system_header_change, system_ephemeral, system_combined_user_activity, etc.
 */
const SYSTEM_MESSAGE_PREFIX = "system_";

//#endregion

//#region Post Type Checks

/**
 * Checks if post is a system message (not user-created).
 * System posts are generated by the server for channel/team events.
 *
 * @param post - Post to check
 * @returns true if post type starts with 'system_'
 *
 * @example
 * ```typescript
 * isSystemPost({ type: 'system_join_channel', ... }) // => true
 * isSystemPost({ type: '', ... }) // => false (regular user post)
 * ```
 */
export function isSystemPost(post: IPost): boolean {
  if (!post.type) {
    return false;
  }
  return post.type.startsWith(SYSTEM_MESSAGE_PREFIX);
}

/**
 * Checks if post is ephemeral (temporary, not persisted).
 * Ephemeral posts are only visible to the current user and disappear on refresh.
 *
 * @param post - Post to check
 * @returns true if post type is 'system_ephemeral'
 *
 * @example
 * ```typescript
 * isEphemeralPost({ type: 'system_ephemeral', ... }) // => true
 * isEphemeralPost({ type: 'system_join_channel', ... }) // => false
 * ```
 */
export function isEphemeralPost(post: IPost): boolean {
  return post.type === "system_ephemeral";
}

/**
 * Checks if post has been edited.
 *
 * @param post - Post to check
 * @returns true if edit_at > 0 and differs from create_at
 *
 * @example
 * ```typescript
 * isPostEdited({ edit_at: 1704067300000, create_at: 1704067200000, ... }) // => true
 * isPostEdited({ edit_at: 0, create_at: 1704067200000, ... }) // => false
 * ```
 */
export function isPostEdited(post: IPost): boolean {
  return post.edit_at > 0 && post.edit_at !== post.create_at;
}

/**
 * Checks if post has been deleted.
 *
 * @param post - Post to check
 * @returns true if delete_at > 0 or state is 'DELETED'
 *
 * @example
 * ```typescript
 * isPostDeleted({ delete_at: 1704067200000, ... }) // => true
 * isPostDeleted({ state: 'DELETED', ... }) // => true
 * isPostDeleted({ delete_at: 0, state: '', ... }) // => false
 * ```
 */
export function isPostDeleted(post: IPost): boolean {
  return post.delete_at > 0 || post.state === "DELETED";
}

/**
 * Checks if post is pinned to the channel.
 *
 * @param post - Post to check
 * @returns true if post is pinned
 *
 * @example
 * ```typescript
 * isPostPinned({ is_pinned: true, ... }) // => true
 * isPostPinned({ is_pinned: false, ... }) // => false
 * ```
 */
export function isPostPinned(post: IPost): boolean {
  return post.is_pinned === true;
}

/**
 * Checks if post is a reply (has a root_id).
 *
 * @param post - Post to check
 * @returns true if post has a non-empty root_id
 *
 * @example
 * ```typescript
 * isPostReply({ root_id: 'abc123', ... }) // => true
 * isPostReply({ root_id: '', ... }) // => false
 * ```
 */
export function isPostReply(post: IPost): boolean {
  return Boolean(post.root_id && post.root_id.length > 0);
}

/**
 * Checks if post is a root post (not a reply).
 *
 * @param post - Post to check
 * @returns true if post has no root_id
 *
 * @example
 * ```typescript
 * isPostRoot({ root_id: '', ... }) // => true
 * isPostRoot({ root_id: 'abc123', ... }) // => false
 * ```
 */
export function isPostRoot(post: IPost): boolean {
  return !isPostReply(post);
}

/**
 * Checks if post failed to send.
 *
 * @param post - Post to check
 * @returns true if post.failed is true
 *
 * @example
 * ```typescript
 * isPostFailed({ failed: true, ... }) // => true
 * isPostFailed({ failed: false, ... }) // => false
 * isPostFailed({ ... }) // => false (undefined)
 * ```
 */
export function isPostFailed(post: IPost): boolean {
  return post.failed === true;
}

//#endregion

//#region Post Priority

/**
 * Checks if post has priority metadata (urgent or important).
 *
 * @param post - Post to check
 * @returns true if post has priority set
 *
 * @example
 * ```typescript
 * hasPostPriority({ metadata: { priority: { priority: 'urgent' } }, ... }) // => true
 * hasPostPriority({ metadata: { priority: { priority: '' } }, ... }) // => false
 * ```
 */
export function hasPostPriority(post: IPost): boolean {
  const priority = post.metadata?.priority?.priority;
  return priority === "urgent" || priority === "important";
}

/**
 * Gets the priority level of a post if set.
 *
 * @param post - Post to get priority from
 * @returns 'urgent', 'important', or null if not set
 *
 * @example
 * ```typescript
 * getPostPriority({ metadata: { priority: { priority: 'urgent' } }, ... }) // => 'urgent'
 * getPostPriority({ metadata: {}, ... }) // => null
 * ```
 */
export function getPostPriority(post: IPost): "urgent" | "important" | null {
  const priority = post.metadata?.priority?.priority;
  if (priority === "urgent" || priority === "important") {
    return priority;
  }
  return null;
}

//#endregion

//#region Post Reactions

/**
 * Checks if post has any reactions.
 *
 * @param post - Post to check
 * @returns true if post has at least one reaction
 *
 * @example
 * ```typescript
 * hasPostReactions({ metadata: { reactions: [{ emoji_name: '+1' }] }, ... }) // => true
 * hasPostReactions({ metadata: { reactions: [] }, ... }) // => false
 * ```
 */
export function hasPostReactions(post: IPost): boolean {
  const reactions = post.metadata?.reactions;
  return Array.isArray(reactions) && reactions.length > 0;
}

/**
 * Gets total count of reactions on a post.
 *
 * @param post - Post to count reactions for
 * @returns Number of reactions
 *
 * @example
 * ```typescript
 * getPostReactionCount({ metadata: { reactions: [{}, {}, {}] }, ... }) // => 3
 * getPostReactionCount({ metadata: {}, ... }) // => 0
 * ```
 */
export function getPostReactionCount(post: IPost): number {
  const reactions = post.metadata?.reactions;
  return Array.isArray(reactions) ? reactions.length : 0;
}

//#endregion

//#region Post Content

/**
 * Gets the effective message to display.
 * Handles special post types that may have different display logic.
 *
 * @param post - Post to get message from
 * @returns The message string to display
 *
 * @example
 * ```typescript
 * getPostMessage({ message: 'Hello world', ... }) // => 'Hello world'
 * getPostMessage({ message: '', state: 'DELETED', ... }) // => ''
 * ```
 */
export function getPostMessage(post: IPost): string {
  // Deleted posts should not show content
  if (isPostDeleted(post)) {
    return "";
  }

  return post.message;
}

/**
 * Gets a plain text preview of post message.
 * Strips markdown formatting and truncates to maxLength.
 *
 * @param post - Post to get preview from
 * @param maxLength - Maximum length of preview (default: 100)
 * @returns Truncated plain text preview
 *
 * @example
 * ```typescript
 * getPostPreview({ message: '**Hello** world', ... }, 10) // => 'Hello w...'
 * getPostPreview({ message: 'Short', ... }, 100) // => 'Short'
 * ```
 */
export function getPostPreview(post: IPost, maxLength = 100): string {
  const message = getPostMessage(post);

  if (!message) {
    return "";
  }

  // Strip common markdown formatting
  // IMPORTANT: Order matters - process image/link syntax BEFORE stripping markers
  const stripped = message
    // Remove image syntax ![alt](url) - MUST be before link removal
    .replace(/!\[[^\]]*\]\([^)]+\)/g, "")
    // Remove link syntax [text](url) -> text
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    // Remove bold/italic/strikethrough/code markers
    .replace(/\*\*|__|\*|_|~~|`/g, "")
    // Remove headers
    .replace(/^#{1,6}\s+/gm, "")
    // Remove blockquotes
    .replace(/^>\s+/gm, "")
    // Remove list markers
    .replace(/^[-*+]\s+/gm, "")
    .replace(/^\d+\.\s+/gm, "")
    // Collapse whitespace
    .replace(/\s+/g, " ")
    .trim();

  return truncateText(stripped, maxLength);
}

/**
 * Extracts hashtags from post.
 * Parses the post.hashtags string which is space-separated.
 *
 * @param post - Post to extract hashtags from
 * @returns Array of hashtag strings (without # prefix)
 *
 * @example
 * ```typescript
 * getPostHashtags({ hashtags: '#react #typescript', ... }) // => ['react', 'typescript']
 * getPostHashtags({ hashtags: '', ... }) // => []
 * ```
 */
export function getPostHashtags(post: IPost): string[] {
  if (!post.hashtags || typeof post.hashtags !== "string") {
    return [];
  }

  const trimmed = post.hashtags.trim();
  if (!trimmed) {
    return [];
  }

  // Split by whitespace and remove # prefix if present
  return trimmed
    .split(/\s+/)
    .map((tag) => (tag.startsWith("#") ? tag.slice(1) : tag))
    .filter(Boolean);
}

//#endregion

//#region Post Timestamp

/**
 * Options for formatting post timestamps.
 */
type IFormatTimestampOptions = {
  locale?: string;
  timeZone?: string;
};

/**
 * Formats post timestamp for display.
 * Uses relative time for recent posts (today/yesterday), absolute for older.
 *
 * @param post - Post to format timestamp for
 * @param options - Locale and timezone options
 * @returns Formatted timestamp string
 *
 * @example
 * ```typescript
 * // If post is from today
 * formatPostTimestamp({ create_at: Date.now() - 3600000, ... }) // => '1 hour ago'
 *
 * // If post is from yesterday
 * formatPostTimestamp({ create_at: yesterdayTimestamp, ... }) // => 'Yesterday at 3:30 PM'
 *
 * // If post is older
 * formatPostTimestamp({ create_at: olderTimestamp, ... }) // => 'January 1, 2024 at 3:30 PM'
 * ```
 */
export function formatPostTimestamp(
  post: IPost,
  options: IFormatTimestampOptions = {},
): string {
  const { locale, timeZone } = options;
  const timestamp = post.create_at;

  // Use relative time for posts from today
  if (isToday(timestamp)) {
    return getRelativeTime(timestamp, { locale });
  }

  // Use "Yesterday" label for yesterday's posts
  if (isYesterday(timestamp)) {
    const time = new Intl.DateTimeFormat(locale, {
      hour: "numeric",
      minute: "2-digit",
      timeZone,
    }).format(timestamp);
    return `Yesterday at ${time}`;
  }

  // Use full date/time for older posts
  return formatDateTime(timestamp, { locale, timeZone });
}

//#endregion

//#region Post Attachments

/**
 * Gets count of file attachments on post.
 * Counts both files in metadata and file_ids array.
 *
 * @param post - Post to count attachments for
 * @returns Number of file attachments
 *
 * @example
 * ```typescript
 * getPostAttachmentCount({ metadata: { files: [{}, {}] }, file_ids: [], ... }) // => 2
 * getPostAttachmentCount({ file_ids: ['a', 'b', 'c'], metadata: {}, ... }) // => 3
 * ```
 */
export function getPostAttachmentCount(post: IPost): number {
  // Prefer metadata.files if available (has full file info)
  const metadataFiles = post.metadata?.files;
  if (Array.isArray(metadataFiles) && metadataFiles.length > 0) {
    return metadataFiles.length;
  }

  // Fall back to file_ids count
  const fileIds = post.file_ids;
  if (Array.isArray(fileIds)) {
    return fileIds.length;
  }

  return 0;
}

/**
 * Extracts FileInfo array from post metadata.
 * Returns empty array if no files are attached.
 *
 * @param post - Post to extract files from
 * @returns Array of file info objects
 *
 * @example
 * ```typescript
 * getPostFileInfos({ metadata: { files: [{ id: '1', name: 'file.txt' }] }, ... })
 * // => [{ id: '1', name: 'file.txt', ... }]
 *
 * getPostFileInfos({ metadata: {}, ... }) // => []
 * ```
 */
export function getPostFileInfos(post: IPost): IFileInfo[] {
  const files = post.metadata?.files;
  if (Array.isArray(files)) {
    return files;
  }
  return [];
}

//#endregion

//#region Combined User Activity

/**
 * Gets combined user activity posts for system_combined_user_activity posts.
 * These are system posts that aggregate multiple join/leave events.
 *
 * @param post - Post to get combined posts from
 * @returns Array of combined posts, or empty array if not applicable
 *
 * @example
 * ```typescript
 * getCombinedPosts({
 *   type: 'system_combined_user_activity',
 *   props: { user_activity_posts: [post1, post2] },
 *   ...
 * }) // => [post1, post2]
 *
 * getCombinedPosts({ type: '', ... }) // => []
 * ```
 */
export function getCombinedPosts(post: IPost): IPost[] {
  if (post.type !== "system_combined_user_activity") {
    return [];
  }

  const combinedPosts = post.props?.user_activity_posts;
  if (Array.isArray(combinedPosts)) {
    return combinedPosts as IPost[];
  }

  return [];
}

//#endregion
